name: Create Archive
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: SetTime
      env:
        TZ: 'Asia/Tokyo'
      run: echo "CURRENT_DATETIME=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - run: echo "RELEASE_FILENAME=release_${{ env.CURRENT_DATETIME }}.zip" >> $GITHUB_ENV

    - name: Inspect files before checkout
      run: ls -la

    - name: show current directory before checkout
      run: pwd

    - name: Checkout
      uses: actions/checkout@v4

    - name: Inspect files after checkout
      run: ls -la

    - name: show current directory after checkout
      run: pwd

    - name: show all branches after checkout
      run: git branch -a

    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: ${{ env.RELEASE_FILENAME }}
        exclusions: '*.git*'

    - name: Inspect files after checkout
      run: ls -la

    - run: |
        echo "${{ secrets.GITHUB_TOKEN }}"
        echo "${{ env.CURRENT_DATETIME }}"
        echo "${{ env.RELEASE_FILENAME }}"
